"""add_notification_events_and_gmf_new_columns

Revision ID: 7023f03b4bbe
Revises: c7d81da711bc
Create Date: 2026-07-07 23:05:47.819034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7023f03b4bbe'
down_revision: Union[str, Sequence[str], None] = 'c7d81da711bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_type', sa.Enum('GMF_DETECTED', 'TEST_GMF_RECEIVED', 'PREVIEW_GENERATED', 'APPROVED', 'REJECTED', 'BATCH_STARTED', 'BATCH_COMPLETED', 'BATCH_FAILED', 'ERROR', name='notification_event_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['billing_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['gmf_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('billing_runs', sa.Column('cycle_number', sa.Integer(), nullable=True))
    op.add_column('billing_runs', sa.Column('output_path', sa.Text(), nullable=True))
    op.add_column('gmf_uploads', sa.Column('cycle_number', sa.Integer(), nullable=True))
    op.add_column('gmf_uploads', sa.Column('template_detected', sa.Text(), nullable=True))
    op.add_column('gmf_uploads', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmf_uploads', 'rejection_reason')
    op.drop_column('gmf_uploads', 'template_detected')
    op.drop_column('gmf_uploads', 'cycle_number')
    op.drop_column('billing_runs', 'output_path')
    op.drop_column('billing_runs', 'cycle_number')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
