"""add admin1 and system settings

Revision ID: 9abe85777f15
Revises: 7023f03b4bbe
Create Date: 2026-07-14 23:37:37.400509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abe85777f15'
down_revision: Union[str, Sequence[str], None] = '7023f03b4bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create template_approval_status enum type first
    op.execute(sa.text(
        "DO $$ BEGIN "
        "  CREATE TYPE template_approval_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    ))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('template_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Alter approval_status column to enum safely
    op.execute("ALTER TABLE invoice_templates ALTER COLUMN approval_status DROP DEFAULT")
    op.execute("ALTER TABLE invoice_templates ALTER COLUMN approval_status TYPE template_approval_status USING approval_status::template_approval_status")
    op.execute("ALTER TABLE invoice_templates ALTER COLUMN approval_status SET DEFAULT 'PENDING'::template_approval_status")
    
    # Custom: Add 'ADMIN1' value to user_role enum
    op.execute("COMMIT") # ALTER TYPE ... ADD VALUE cannot run inside a transaction block in older postgres/alembic unless we commit first, but op.execute handles it
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'ADMIN1'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_templates', 'approval_status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='template_approval_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_table('template_history')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
