"""Add template fields

Revision ID: de4394329a97
Revises: f0a1b2c3d4e5
Create Date: 2026-07-05 02:55:45.432898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4394329a97'
down_revision: Union[str, Sequence[str], None] = 'f0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    template_category = postgresql.ENUM('CLASSIC', 'MODERN', 'ENTERPRISE', 'MINIMAL', 'CUSTOM', name='template_category')
    template_category.create(op.get_bind(), checkfirst=True)
    op.add_column('invoice_templates', sa.Column('category', sa.Enum('CLASSIC', 'MODERN', 'ENTERPRISE', 'MINIMAL', 'CUSTOM', name='template_category'), server_default='CLASSIC', nullable=False))
    op.add_column('invoice_templates', sa.Column('layout_type', sa.Text(), server_default='default', nullable=False))
    op.add_column('invoice_templates', sa.Column('cover_image_url', sa.Text(), nullable=True))
    op.add_column('invoice_templates', sa.Column('template_layout', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_templates', 'template_layout')
    op.drop_column('invoice_templates', 'cover_image_url')
    op.drop_column('invoice_templates', 'layout_type')
    op.drop_column('invoice_templates', 'category')
    template_category = postgresql.ENUM('CLASSIC', 'MODERN', 'ENTERPRISE', 'MINIMAL', 'CUSTOM', name='template_category')
    template_category.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

